### PR TITLE
WL-3474 New web content tool will not accept URLs with spaces

### PR DESCRIPTION
**Pull request by nicholaswilson100**
Bug in code is that it escapes the url and then validates on something else

### CODE REVIEW

**Comment by buckett** [comment]
Am I right in thinking that this change will allow un-escaped URLs to be stored in the DB un-escaped?

If so then don't we still have the problem that the tool doesn't correctly display a unescaped URL?

**Comment by nicholaswilson100** [comment]
An unescaped URL with spaces in seems to display okay. 

Here's what I did (if this is the right test...)

I created a HTML page in Resources called 'new_page with spaces.html',  clicked on it and the URL was 'http://localhost:8080/access/content/group/f47d0797-299f-4b77-a5a8-767a2a80bc99/new_page with spaces.html' and then copied '/access/content/group/f47d0797-299f-4b77-a5a8-767a2a80bc99/new_page with spaces.html' into the Site Info URL and saved it and on the Home page it showed the text content I had put in.

(I'm not sure if it saves the relative URL in the DB with spaces in or if it escapes it first but I can find out.)

**Comment by buckett** [comment]
Ok, what's strange is that https://jira.oucs.ox.ac.uk/jira/browse/WL-3451 seems to be saying URLs with spaces don't work.

**Comment by nicholaswilson100** [comment]
Do you think it's possible different comments were  written  using different Web Content tools on staging2?  

When I go through the WL-3451 description, there's a file with spaces in it already there  in the Site Info URL and it shows up fine on the Home page but you can't save it because you get the Alert: Invalid URL message.

**Comment by buckett** [comment]
There original issue doesn't seem reproducable. 

If we want to allow people to enter URLs with spaces in them then we should be escaping them when we store them so the DB continues to contain syntactically value URLs.

**Pull request closed without merging**
